# Generated by Django 6.0.6 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="management_token_hash",
            field=models.CharField(blank=True, default="", editable=False, max_length=64),
        ),
    ]
