# Generated by Django 6.0.6 on 2026-07-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_invitation_management_token_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="response_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("responded_at__isnull", True),
                        ("response_status", "pending"),
                    )
                    | models.Q(
                        ("responded_at__isnull", False),
                        ("response_status__in", ("accepted", "declined")),
                    )
                ),
                name="invitation_response_state_consistent",
            ),
        ),
    ]
