# Generated by Django 6.0.6 on 2026-07-22

import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_invitation_response_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="message",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.CreateModel(
            name="InvitationPlanOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("place", models.CharField(max_length=200)),
                ("comment", models.CharField(blank=True, default="", max_length=500)),
                ("position", models.PositiveSmallIntegerField()),
                ("selected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_options",
                        to="common.invitation",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("invitation", "position"),
                        name="unique_invitation_plan_option_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(position__gte=0, position__lte=4),
                        name="invitation_plan_option_position_range",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(selected_at__isnull=False),
                        fields=("invitation",),
                        name="unique_selected_plan_option_per_invitation",
                    ),
                ],
            },
        ),
    ]
