# Generated by Django 6.0.6 on 2026-07-23

import django.utils.timezone
from django.db import migrations, models


def preserve_existing_publication_time(apps, schema_editor):
    """Treat pre-lifecycle invitations as published since their original creation."""
    Invitation = apps.get_model("common", "Invitation")
    database_alias = schema_editor.connection.alias
    Invitation.objects.using(database_alias).filter(published_at__isnull=True).update(
        published_at=models.F("created_at"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_invitation_creation_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="publication_status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            preserve_existing_publication_time,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="invitation",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        publication_status="draft",
                        published_at__isnull=True,
                    )
                    | models.Q(
                        publication_status="published",
                        published_at__isnull=False,
                    )
                ),
                name="invitation_publication_state_consistent",
            ),
        ),
    ]
