# Generated by Django 6.0.6 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):
    """Persist when an invitation author intends to prepare date options."""

    dependencies = [
        ("common", "0009_invitation_screen_secondary_button_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="planning_mode",
            field=models.CharField(
                choices=[
                    ("before_acceptance", "Before acceptance"),
                    ("after_acceptance", "After acceptance"),
                ],
                default="after_acceptance",
                max_length=17,
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    planning_mode__in=(
                        "before_acceptance",
                        "after_acceptance",
                    )
                ),
                name="invitation_planning_mode_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(creation_mode="extended")
                    | models.Q(planning_mode="after_acceptance")
                ),
                name="quick_invitation_plans_after_acceptance",
            ),
        ),
    ]
