# Generated by Django 6.0.6 on 2026-07-26

import django.db.models.deletion
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    """Add ordered activity ideas owned by one invitation."""

    dependencies = [
        ("common", "0010_invitation_planning_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, default="", max_length=500)),
                ("image_key", models.CharField(blank=True, default="", max_length=80)),
                ("place", models.CharField(blank=True, default="", max_length=200)),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("external_url", models.URLField(blank=True, default="", max_length=500)),
                ("position", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_options",
                        to="common.invitation",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("invitation", "position"),
                        name="unique_invitation_activity_option_position",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(position__gte=0, position__lte=5),
                        name="invitation_activity_option_position_range",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(estimated_price__isnull=True)
                            | models.Q(estimated_price__gte=0)
                        ),
                        name="invitation_activity_option_price_nonnegative",
                    ),
                ],
            },
        ),
    ]
