# Generated by Django 6.0.6 on 2026-07-26

from django.db import migrations, models


class Migration(migrations.Migration):
    """Store one mutable recipient activity selection per invitation."""

    dependencies = [
        ("common", "0011_activityoption"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityoption",
            name="selected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="activityoption",
            constraint=models.UniqueConstraint(
                condition=models.Q(selected_at__isnull=False),
                fields=("invitation",),
                name="unique_selected_activity_option_per_invitation",
            ),
        ),
    ]
